### ISSUE TITLE
Finobe starts and shuts down after few seconds

### ISSUE THREAD

**Issue by azbestoid** [LeadRDRK/finobe-linux-wrapper#4]
I installed it normally as I should with `./winenobe.sh 2016` and after pressing "Play" on the website (in Firefox) it opens Finobe and closes after few seconds.I tried installing it again but the shell script says that it's already installed and I don't know how to uninstall it. I'm using Manjaro and I have all of the dependencies installed.

**Comment by Techwizz-somboo** [comment]
Yeah I have the same issue, was just talking about it on their Discord server. I don't currently know a fix. To uninstall do `winenobe --uninstall all 2016`

**Comment by Techwizz-somboo** [comment]
Oh and I'm on Arch (basically the same as Manjaro)

**Comment by Techwizz-somboo** [comment]
Just tested on Ubuntu 18.04, so it's confirmed it's not a Arch/Arch derivative issue.

**Comment by LeadRDRK** [comment]
This is a Wine issue. We can't do anything except waiting for Wine/Finobe to fix it, sorry.

**Comment by azbestoid** [comment]
Oh, okay. If I manage to fix it somehow I'll post the fix here.
